### ISSUE TITLE
discussion

### ISSUE THREAD

**Issue by hrk0531** [hrk0531/SapPy#11]
@yanagikad 
- **sappy/dimension/rotator.py**の中で関数**orthogonal_converge**を定め収束基準を戻り値としたがどのように使えば良いかわからない。
- 関数**orthogonal_rotation**の中の`u[t, s] = x[t, j-1, s]**2 - x[t, j-2, s]**2`について、`too many indices for array: array is 2-dimensional, but 3 were indexed`とエラーが出る。indeciesを減らせばいいのだが、数式
```math
u_{p(i)} = f^{*2}_{pj(i)} - f^{*2}_{pk(i)}
```
を維持したい。

**Comment by yanagikad** [comment]
@hrk0531 
まずブランチ名を明記して欲しいのと、パスもそうだが該当箇所のリンクを貼って欲しい。

1つ目について
「どうしたらいいのかわからない」についてもう少し解像度を上げて欲しい。
結局
- 何が欲しくて、
- 何を与えて、
- そのためにどんな処理を今していて
- 何に困っているか
を教えて欲しい。

2つ目もただエラーと要望を書いているが
その結果を受けて自分なりに解釈してfixしてみた結果、何に困ったのかをより詳細に書いて欲しい

**Comment by yanagikad** [comment]
あとdiscussionのところでやってると思ってタイトルスルーしたけどissueなんだねw

issueの方に上げるならもうちょいタイトルちゃんと書いて。何のdiscussionやってるかわからん。

**Comment by hrk0531** [comment]
新しく建ててクローズします
