### ISSUE TITLE
Write draft-level README

### ISSUE THREAD

**Issue by yanagikad** [hrk0531/sappy#2]
Create README.md about deaft including about Project.

**Comment by yanagikad** [comment]
READMEの存在を確認

**Comment by hrk0531** [comment]
まだ煮詰まってないから依存関係とか機械的なことしか書けてない。徐々に書きます。

**Comment by yanagikad** [comment]
@hrk0531 
ドラフトレベルだから用意しとけってぐらいのニュアンスやで

**Comment by yanagikad** [comment]
準備中の時はWIPって書いとこう

**Comment by hrk0531** [comment]
コミットメッセージにでOK？

**Comment by yanagikad** [comment]
@hrk0531 
READMEに。
論文でも最初骨組み立てるでしょ？
でも詳細書けない部分はあって、そこにWIPって書いとく。
あとメンションつけてくれないと通知こない

**Comment by yanagikad** [comment]
コミットメッセージはわかるように書いといて。
